### PR TITLE
Updated to 0.12

### PR DESCRIPTION
**Pull request by brooksmtownsend**
Signed-off-by: Brooks Townsend <brooks@cosmonic.com>

### CODE REVIEW

**Review by mattwilkinsonn — APPROVED** [review]

**Comment by mattwilkinsonn** [comment]
non blocking: is there any way we can automate this stuff?

**Comment by thomastaylor312** [comment]
@mattwilkinsonn I am sure there is, but we just haven't put the effort into it yet. Also, I should add you as a maintainer on this repo

**Comment by brooksmtownsend** [comment]
@mattwilkinsonn yeah I'd love to automate this and the homebrew repository

**Comment by jordan-rash** [comment]
I can work on the homebrew automation

**Pull request merged**
